
[31mStart to train the network


[5/5] Loss: 0.7833: 100%|====================| 5/5 [00:05<00:00,  1.13s/it]
[34mEpoch [1/5]
     Train Loss: 0.8045 - Validation Loss: 0.1558
     Train LossMSE: 0.1647 - Validation LossMSE: 0.1428
     Train PSNR: 7.8978 - Validation PSNR: 8.4539
     Train SSIM: 0.0729 - Validation SSIM: 0.2480
[32m     New Best Validation PSNR: 8.4539 

[5/5] Loss: 0.6147: 100%|====================| 5/5 [00:04<00:00,  1.07it/s]
[34mEpoch [2/5]
     Train Loss: 0.6767 - Validation Loss: 187.2387
     Train LossMSE: 0.0507 - Validation LossMSE: 0.0338
     Train PSNR: 14.0902 - Validation PSNR: 14.7213
     Train SSIM: 0.3632 - Validation SSIM: 0.4854
[32m     New Best Validation PSNR: 14.7213 

[5/5] Loss: 0.5420: 100%|====================| 5/5 [00:04<00:00,  1.07it/s]
[34mEpoch [3/5]
     Train Loss: 0.5678 - Validation Loss: 58.0973
     Train LossMSE: 0.0151 - Validation LossMSE: 0.0319
     Train PSNR: 18.2456 - Validation PSNR: 14.9593
     Train SSIM: 0.3297 - Validation SSIM: 0.1665
[32m     New Best Validation PSNR: 14.9593 


[5/5] Loss: 0.5048: 100%|====================| 5/5 [00:04<00:00,  1.08it/s]
[34mEpoch [4/5]
     Train Loss: 0.5190 - Validation Loss: 12.9627
     Train LossMSE: 0.0134 - Validation LossMSE: 0.0273
     Train PSNR: 18.7426 - Validation PSNR: 15.6410
     Train SSIM: 0.2054 - Validation SSIM: 0.1383
[32m     New Best Validation PSNR: 15.6410 


[5/5] Loss: 0.5001: 100%|====================| 5/5 [00:04<00:00,  1.07it/s]
[34mEpoch [5/5]
     Train Loss: 0.5002 - Validation Loss: 2.9945
     Train LossMSE: 0.0136 - Validation LossMSE: 0.0196
     Train PSNR: 18.6833 - Validation PSNR: 17.0871
     Train SSIM: 0.1921 - Validation SSIM: 0.1596
[32m     New Best Validation PSNR: 17.0871 
[31mThe network is trained
>> read:  E:\mvtec_anomaly_detection\runtime\test\defective\000_mask.png
>> folder:  E:\mvtec_anomaly_detection\runtime\test\defective
>> file:  000.png
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\main.py", line 86, in call_training
    myNet.evaluate(resultPath = resultPath, printPrediction = True)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 239, in evaluate
    allInputs, allPreds, allLabels, allMasks = self.getPrediction(self.testlDataLoader, resultPath)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 205, in getPrediction
    for (corrupted, image, mask, label) in dataLoader:
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\datasets\dataLoader.py", line 63, in __getitem__
    mask     = np.expand_dims(cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY),-1)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'